#!/bin/bash

# Update system
echo "Updating system"
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
echo ""

# Move config directories
echo "Moving Config Directories"
#cp -r .config/ ../
cp -r .fonts/ ../
cp .bashrc ../
cp .vimrc ../
cp .Xdefaults ../
cp .profile ../
echo ""

# Install required programs
echo "Install Curl"
sudo apt-get install curl
echo ""

# Install additional programs
echo "Installing Vim"
sudo apt-get install vim
echo ""

echo "Installing Vim pluging Manager"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo ""

echo "Installing i3"
sudo apt-get install i3
echo ""

echo "Installing Feh"
sudo apt-get install feh
echo ""

echo "Installing urxvt 256"
sudo apt-get install rxvt-unicode-256color
echo ""

echo "Installing Ranger"
sudo apt-get install ranger
echo ""

#echo "Installing Mpd and Ncmpcpp"
#sudo apt-get install mpd ncmpcpp
#echo ""

echo "Installing Zathura"
sudo apt-get install zathura zathura-djvu zathura-pdf-poppler
echo ""

echo "Installing Git"
sudo apt-get install git
echo ""

echo "Installing Tldr"
sudo apt-get install tldr
echo ""


