#!/bin/bash

# Update system
echo "Updating system"
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
echo ""

# Install utility programs
echo "Install Curl"
sudo apt-get install curl
echo ""

# Installing additional programs
echo "Installing Vim"
sudo apt-get install vim
echo ""

echo "Installing Vim pluging Manager"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo ""

echo "Installing Git"
sudo apt-get install git
echo ""

echo "Installing Tldr"
sudo apt-get install tldr
echo ""
