#!/bin/bash

# Update system
echo "Updating system"
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
echo ""

# Move config directories
echo "Moving Config Directories"
#cp -r .config/ $HOME
cp -r .fonts/ $HOME
cp .bashrc $HOME
cp .vimrc $HOME
cp .Xdefaults $HOME
cp .profile $HOME
echo ""

# Install Packages:

################################################################################
# General system applications
################################################################################

echo "Installing Curl"
sudo apt-get install curl
echo ""

# Required for installing st
echo "Installing libxft-dev font drawing library"
sudo apt-get install libxft-dev
echo ""

echo "Installing Vim"
sudo apt-get install vim
echo ""

echo "Installing Vim-gtk"
sudo apt-get install vim-gtk
echo ""

echo "Installing Vim-gtk3"
sudo apt-get install vim-gtk3
echo ""

echo "Installing Vim Pluging Manager"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo ""

echo "Installing the Powerline Patched font Hack"
sudo apt-get install fonts-hack-ttf
echo ""

# Maybe unnecessary since I have Hack font
echo "Installing Powerline Fonts"
sudo apt-get install fonts-powerline
echo ""

echo "Installing i3"
sudo apt-get install i3
echo ""

echo "Installing i3blocks"
sudo apt-get install i3blocks
echo ""

echo "Installing Compton"
sudo apt-get install compton
echo ""

echo "Installing Feh"
sudo apt-get install feh
echo ""

echo "Installing Ranger"
sudo apt-get install ranger
echo ""

echo "Installing Cmus"
sudo apt-get install cmus
echo ""

echo "Installing Zathura"
sudo apt-get install zathura zathura-djvu zathura-pdf-poppler
echo ""

echo "Installing Vlc"
sudo apt-get install vlc
echo ""

echo "Installing Git"
sudo apt-get install git
echo ""

echo "Installing Tldr"
sudo apt-get install tldr
echo ""

echo "Installing Neofetch"
sudo apt-get install neofetch
echo ""

echo "Installing Cowsay"
sudo apt-get install cowsay
echo ""

echo "Installing Xinput"
sudo apt-get install xinput
echo ""

echo "Installing Autocutsel"
sudo apt-get install autocutsel
echo ""

echo "Installing Qbittorrent"
sudo apt-get install qbittorrent
echo ""

echo "Installing Tree"
sudo apt-get install tree
echo ""

echo "Installing Qutebrowser"
sudo apt-get install qutebrowser
echo ""

echo "Installing Autojump"
sudo apt-get install autojump
echo ""

echo "Fzf"
sudo apt-get install fzf
echo ""

################################################################################
# For Python
################################################################################
echo "Installing Pip"
sudo apt-get install python3-pip
echo ""

echo "Pip-installing Pipenv under user"
pip3 install --user pipenv
echo ""

################################################################################
# For JavaScript
################################################################################
# Debian repo has version 10.x thus,
echo "Installing NodeJS"
curl -sL https://deb.nodesource.com/setup_13.x | bash -
apt-get install -y nodejs
echo ""

echo "Installing Npm"
sudo apt-get install npm
echo ""

echo "Installing Livedown"
sudo npm install -g livedown
echo ""

################################################################################
# LaTeX
################################################################################
echo "Installing TexLive"
sudo apt-get install texlive-full
echo ""

echo "Congratulations! Your GNU/Linux configuration is all done!" | cowsay -f tux


